platform :ios,'7.0'

pod 'AFNetworking', '~> 2.0.3'
pod 'Reachability', '~> 3.1.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'SFHFKeychainUtils', '~> 0.0.1'
pod 'MagicalRecord', '~> 2.2'
pod 'iOS7Colors', '~> 2.1.0'
pod 'UMengSocial', '~> 3.1'
pod 'BlocksKit', '~> 2.0.0'
pod 'ConciseKit', '~> 0.1.2'
